steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform
      terraform init -input=false
                
- id: 'tf plan'
  name: 'hashicorp/terraform:1.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd terraform
      terraform plan -input=false -out=clould_run_book.tfplan

- id: 'store tfplan file'
  name: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
  entrypoint: sh
  args:
  - -c
  - |
      gsutil cp cloud_run_book.tfplan gs://tf-plan

serviceAccount: cloud-run-book@${PROJECT_ID}.iam.gserviceaccount.com
options:
  env: ['TF_IN_AUTOMATION=1']
  logging: CLOUD_LOGGING_ONLY
